### ISSUE TITLE
人体关键点载入

### ISSUE THREAD

**Issue by BerryRB** [DataLoaderX/datasetsome#10]
博主您好，看了您的博客过来的，请问在载入人体关键点注释的时候，如果segmentation是RLE格式该怎么载入呢

**Comment by xinetzone** [comment]
RLE格式的文件没有研究过，您可以提供一个简单的样本，我使用 Python 解析一下试试

**Comment by BerryRB** [comment]
@xinetzone 
![000000250282](https://user-images.githubusercontent.com/34699510/69721072-fdb76f80-114e-11ea-9d90-c877f5c8e9f2.jpg)

[view_rle.txt](https://github.com/DataLoaderX/datasetsome/files/3896709/view_rle.txt)

这是我截取出来的一段注释，txt改为json就能正常使用了，上面是对应的图片，谢谢！

**Comment by xinetzone** [comment]
好的，问题解决就太棒了。感谢您为本项目提供了一个新的问题，并能够自行解决。

如果没有其它问题，该 Issue 可以关闭了吗？

**Comment by BerryRB** [comment]
@xinetzone 额....我的意思是上面的txt后缀改为json就是这正常的注释了，以为这个系统没法上传json文件。前面您说让我提供一个简单的样本，上面就是我提供的一个关于RLE标注格式的样本

**Comment by xinetzone** [comment]
@BerryRB segmentation 格式的数据如果是一个单个的对象（即 `iscrowd=0`，将使用 polygons 格式），如果是一组对象（即 `iscrowd=1`，将使用 RLE 格式）。故而，COCO API 是适用于 RLE 格式的，您可以直接使用。具体使用可参考 [RLE.ipynb](https://github.com/DataLoaderX/datasetsome/blob/master/coco/RLE.ipynb) 和 [RLE_decode.ipynb](https://github.com/DataLoaderX/datasetsome/blob/master/coco/RLE_decode.ipynb)。

**Comment by BerryRB** [comment]
@xinetzone 好的，十分感谢！！！
